### PR TITLE
Add basic Profile page styling structure

### PR DESCRIPTION
**Pull request by Dfredude**
profilePage drawio

### CODE REVIEW

**Review by yuheng-w — APPROVED** [review]
Everything look good to me

**Comment by Dfredude** [comment]
This is the hierarchy updated
profilePage drawio (1)

**Review by yuheng-w — COMMENTED** [review]
Border of input-field input looks a bit too thick in my opnion, everything else look good to me!

**Review by yuheng-w — APPROVED** [review]
Everything look good to me

**Pull request merged**
